// Generated by CoffeeScript 1.7.1
(function() {
  var LIVERELOAD_PORT, lrSnippet, mountFolder;

  LIVERELOAD_PORT = 35729;

  lrSnippet = require("connect-livereload")({
    port: LIVERELOAD_PORT
  });

  mountFolder = function(connect, dir) {
    return connect["static"](require("path").resolve(dir));
  };

  module.exports = function(grunt) {
    var yeomanConfig;
    require("time-grunt")(grunt);
    require("load-grunt-tasks")(grunt);
    yeomanConfig = {
      app: "app",
      dist: "dist",
      tmp: '.tmp'
    };
    grunt.initConfig({
      yeoman: yeomanConfig,
      watch: {
        styles: {
          files: ["<%= yeoman.app %>/styles/{,*/}*.css"],
          tasks: ["copy:styles"]
        },
        livereload: {
          files: ["<%= yeoman.app %>/*.html", "<%= yeoman.app %>/{,*/}{,*/}{,*/}*.css", "<%= yeoman.app %>/{,*/}{,*/}{,*/}*.js", "<%= yeoman.app %>/images/{,*/}*.{png,jpg,jpeg,gif,webp,svg}"]
        }
      },
      connect: {
        options: {
          port: 3001,
          hostname: "0.0.0.0"
        },
        livereload: {
          options: {
            keepalive: true,
            livereload: LIVERELOAD_PORT,
            middleware: function(connect) {
              return [mountFolder(connect, yeomanConfig.tmp), mountFolder(connect, yeomanConfig.app)];
            }
          }
        },
        dist: {
          options: {
            middleware: function(connect) {
              return [mountFolder(connect, yeomanConfig.dist)];
            }
          }
        }
      },
      open: {
        server: {
          path: "http://localhost:<%= connect.options.port %>"
        }
      },
      clean: {
        dev: {
          files: [
            {
              dot: true,
              src: [".tmp"]
            }
          ]
        },
        dist: {
          files: [
            {
              dot: true,
              src: [".tmp", "<%= yeoman.dist %>/*"]
            }
          ]
        },
        server: ".tmp"
      },
      useminPrepare: {
        options: {
          dest: "<%= yeoman.dist %>",
          staging: "<%= yeoman.dist %>",
          flow: {
            steps: {
              css: ['concat'],
              js: ['concat']
            },
            post: {}
          }
        },
        html: "<%= yeoman.app %>/index.html"
      },
      usemin: {
        html: ["<%= yeoman.dist %>/index.html"]
      },
      copy: {
        dist: {
          files: [
            {
              expand: true,
              dot: true,
              cwd: "<%= yeoman.app %>",
              dest: "<%= yeoman.dist %>",
              src: ["*.{ico,png,txt}", "index.html", ".htaccess", "images/{,*/}*.{webp,gif}"]
            }
          ]
        }
      }
    });
    grunt.registerTask("server", ["open", "connect:livereload"]);
    grunt.registerTask("buildDev", ["clean:dev"]);
    grunt.registerTask("dist", ["clean:dist", "copy:dist", "useminPrepare", "concat", "usemin"]);
    return grunt.registerTask("default", ["clean", "buildDev", "server"]);
  };

}).call(this);
