// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('prince', []).constant('cfg', {
    title: 'The Prince',
    cellCount: 6
  }).controller('MainController', function($scope, gameBoard, Piece, PieceDefinitions) {
    $scope.definitions = PieceDefinitions;
    $scope.newPiece = $scope.definitions.bowman;
    $scope.addPiece = function() {
      console.log("addPiece");
      return gameBoard.pieces.push(new Piece({
        type: $scope.newPiece.type,
        x: 0,
        y: 0
      }));
    };
    gameBoard.pieces.push(new Piece({
      type: PieceDefinitions.TYPES.prince,
      x: 3,
      y: 5
    }));
    return gameBoard.pieces.push(new Piece({
      type: PieceDefinitions.TYPES.footman,
      x: 2,
      y: 5
    }));
  });

}).call(this);
