// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('prince').factory('PieceDefinitions', function() {
    var ACTIONS, TYPES, c, definitions, j, m, s, x;
    TYPES = {
      prince: 'prince',
      footman: 'footman',
      pikeman: 'pikeman'
    };
    ACTIONS = {
      move: 'move',
      slide: 'slide',
      jump: 'jump',
      jumpslide: 'jumpslide',
      strike: 'strike',
      command: 'command'
    };
    m = ACTIONS.move;
    s = ACTIONS.slide;
    j = ACTIONS.jump;
    x = ACTIONS.strike;
    c = ACTIONS.command;
    definitions = {
      TYPES: TYPES,
      ACTIONS: ACTIONS,
      footman: {
        actions: [
          {
            move: [[0, -1], [1, 0], [0, 1], [-1, 0]]
          }, {
            move: [[1, 0], [0, 1], [0, 1], [-1, 0]]
          }
        ]
      }
    };
    return definitions;
  });

}).call(this);
