// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('prince').factory('Piece', function(cfg, PieceDefinitions) {
    var Piece;
    Piece = function(options) {
      this.type = options.type;
      this.x = options.x;
      return this.y = options.y;
    };
    Piece.prototype = {
      x: void 0,
      y: void 0,
      actions: 0,
      getSide: function() {
        if (this.actions % 2 === 0) {
          return 0;
        } else {
          return 1;
        }
      },
      move: function(pos) {
        if (pos.x < 0) {
          return 'off the left';
        }
        if (pos.x > cfg.boardSize - 1) {
          return 'off the right';
        }
        if (pos.y < 0) {
          return 'off the top';
        }
        if (pos.y > cfg.boardSize - 1) {
          return 'off the bottom';
        }
        if (!((pos.x != null) && (pos.y != null))) {
          return 'missing a position';
        }
        if (pos.x === this.x && pos.y === this.y) {
          return 'already in this position';
        } else {
          this.x = pos.x;
          this.y = pos.y;
          return this.actions++;
        }
      },
      team: 0
    };
    return Piece;
  }).directive('piece', function(cfg) {
    return {
      restrict: 'A',
      link: function(scope, el, attrs) {
        var draggie, setPosition;
        draggie = new Draggabilly(el[0]);
        draggie.on('dragEnd', function(draggie, evt, pointer) {
          var col, pos, row;
          if (!cfg.pieceSize) {
            console.warn('can not position piece without knowing size');
          }
          col = Math.round(draggie.position.x / cfg.pieceSize);
          if ((0 < col && col > cfg.cellCount)) {
            col = null;
          }
          row = Math.round(draggie.position.y / cfg.pieceSize);
          if ((0 < row && row > cfg.cellCount)) {
            row = null;
          }
          pos = {
            x: col,
            y: row
          };
          return setPosition(pos);
        });
        return setPosition = function(pos) {
          draggie.element.style.left = null;
          draggie.element.style.top = null;
          if (!((pos.x != null) && (pos.y != null))) {
            return;
          }
          return scope.$apply(function() {
            return console.log(scope.piece.move(pos));
          });
        };
      }
    };
  });

}).call(this);
