// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('prince').factory('PieceDefinitions', function() {
    var ACTIONS, TYPES, definitions;
    TYPES = {
      prince: 'prince',
      footman: 'footman',
      pikeman: 'pikeman'
    };
    ACTIONS = {
      move: 'move',
      slide: 'slide',
      jump: 'jump',
      jumpslide: 'jumpslide',
      strike: 'strike',
      command: 'command'
    };
    definitions = {
      TYPES: TYPES,
      ACTIONS: ACTIONS,
      prince: {
        type: TYPES.prince,
        actions: [
          {
            slide: [-1, 0]
          }, [1, 0], {
            slide: [0, 1]
          }, [0, -1]
        ]
      },
      footman: {
        type: TYPES.footman,
        actions: [
          {
            move: [[0, -1], [1, 0], [0, 1], [-1, 0]]
          }, {
            move: [[1, 0], [0, 1], [0, 1], [-1, 0]]
          }
        ]
      }
    };
    return definitions;
  });

}).call(this);
